"""
con.executescript ejecuta varias queries de una sola vez.
SQLite no tiene tipo DATE ni DATETIME como mySQL, así que va con texto.
También pongo un nombre de usuario y una combinación usuario-calificación única para
que no hayan varias calificaciones por usuario.
"""

import sqlite3

con = sqlite3.connect("cine.db")
con.execute("PRAGMA foreign_keys = ON")

con.executescript("""
CREATE TABLE IF NOT EXISTS PERSONAS (
    ID_PERSONA INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_USUARIO TEXT NOT NULL UNIQUE,
    PASSWORD_HASH TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PELICULAS (
    ID_PELICULA TEXT PRIMARY KEY,
    NOMBRE TEXT NOT NULL,
    ANIO INTEGER
);

CREATE TABLE IF NOT EXISTS COMENTARIOS (
    ID_COMENTARIO INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PELICULA TEXT NOT NULL REFERENCES PELICULAS(ID_PELICULA),
    ID_PERSONA INTEGER NOT NULL REFERENCES PERSONAS(ID_PERSONA),
    COMENTARIO TEXT NOT NULL,
    FECHA_CREACION TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CALIFICACIONES (
    ID_CALIFICACION INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PELICULA TEXT NOT NULL REFERENCES PELICULAS(ID_PELICULA),
    ID_PERSONA INTEGER NOT NULL REFERENCES PERSONAS(ID_PERSONA),
    CALIFICACION INTEGER NOT NULL CHECK (CALIFICACION BETWEEN 1 AND 5),
    FECHA_CREACION TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ID_PERSONA, ID_PELICULA)
);
""")

con.commit()
con.close()